export { default as splashScreenReducer } from './splash-screen-slice';
export {
  fetchSplashStatus,
  setStatus,
  setProgress,
  setError,
  setLoading,
  show,
  hide,
  complete,
  clearError,
  reset,
  selectSplashScreenState,
  selectSplashStatus,
  selectSplashProgress,
  selectSplashLoading,
  selectSplashError,
  selectSplashVisible,
  selectSplashDuration,
  selectIsSplashComplete,
} from './splash-screen-slice';
